#!/bin/bash
### BEGIN INIT INFO
# Provides:          thingsboard
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop/restart/status thingsboard server
### END INIT INFO

# Define some variables
USER=thingsboard
JAR_PATH=/usr/share/thingsboard/bin/thingsboard.jar
PIDFILE=/var/run/thingsboard.pid

# Function to check status of the service
status() {
  if [ -f $PIDFILE ]; then
    echo "thingsboard server is running with PID $(cat $PIDFILE)"
  else
    echo "thingsboard server is not running."
  fi
}

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting thingsboard server"
    if [ -f $PIDFILE ]; then
      echo "thingsboard server is already running."
    else
      su -s /bin/bash $USER -c "nohup java -jar $JAR_PATH > /dev/null 2>&1 &"
      echo $! >$PIDFILE
      echo "thingsboard server started."
    fi
    ;;
  stop)
    echo "Stopping thingsboard server"
    if [ ! -f $PIDFILE ]; then
      echo "thingsboard server is not running."
    else
      kill $(cat$PIDFILE)
      rm $PIDFILE
      echo "thingsboard server stopped."
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: /etc/init.d/thingsboard {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
